import type { GetStaticProps } from 'next'
import Head from 'next/head'
import Hero from './components/Hero'
import { Livvic } from 'next/font/google'
import Header from './components/Header'
import AboutMe from './components/AboutMe'
import ContactMe from './components/ContactMe'
import Projects from './components/Projects'
import { About, Contact, PageInfo, Project, Skill, Social } from '@/typings'
import { fetchPageInfo } from '@/utils/fetchPageInfo'
import { fetchAbout } from '@/utils/fetchAbout'
import { fetchSkills } from '@/utils/fetchSkills'
import { fetchProjects } from '@/utils/fetchProjects'
import { fetchSocials } from '@/utils/fetchSocials'
import { fetchContact } from '@/utils/fetchContact'

const livvic = Livvic({
  subsets: ['latin'],
  weight: ['500'],
  style: 'normal',
})

type Props = {
  pageInfo: PageInfo
  about: About
  projects: Project[]
  contact: Contact
  skills: Skill[]
  socials: Social[]
}

const Home = ({
  pageInfo,
  about,
  contact,
  projects,
  skills,
  socials,
}: Props) => {
  return (
    <div className="scroll-smooth h-screen snap-y snap-mandatory">
      <Head>
        <title>Gonzalo Vidal - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section
        id="hero"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-start `}
      >
        <Hero pageInfo={pageInfo} />
      </section>
      <section
        id="about"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-start `}
      >
        <AboutMe about={about} />
      </section>
      <section
        id="projects"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-center `}
      >
        <Projects projects={projects} />
      </section>
      <section
        id="contact"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-center relative before:absolute before:h-10 before:top-0 before:left-0 before:right-0 before:shadow-shading`}
      >
        <ContactMe contact={contact} />
      </section>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo()
  const about: About = await fetchAbout()
  const projects: Project[] = await fetchProjects()
  const contact: Contact = await fetchContact()
  const skills: Skill[] = await fetchSkills()
  const socials: Social[] = await fetchSocials()
  return {
    props: {
      pageInfo,
      about,
      projects,
      contact,
      skills,
      socials,
    },
    revalidate: 10,
  }
}
