import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from './components/Hero'
import { Livvic } from 'next/font/google'
import Header from './components/Header'
import About from './components/About'
import Contact from './components/Contact'
import Projects from './components/Projects'
import Footer from './components/Footer'

const livvic = Livvic({
  subsets: ['latin'],
  weight: ['500'],
  style: 'normal',
})

const Home: NextPage = () => {
  return (
    <div className="scroll-smooth h-screen snap-y snap-mandatory">
      <Head>
        <title>Gonzalo Vidal - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section
        id="hero"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-start `}
      >
        <Hero />
      </section>
      <section
        id="about"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-start `}
      >
        <About />
      </section>
      <section
        id="projects"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-center `}
      >
        <Projects />
      </section>
      <section
        id="contact"
        className={`${livvic.className} font-sans flex items-center bg-[#f6f3ee] snap-center relative before:absolute before:h-10 before:top-0 before:left-0 before:right-0 before:shadow-shading`}
      >
        <Contact />
      </section>
    </div>
  )
}

export default Home
